### ISSUE TITLE
 Solicitar plaza en un viaje

### ISSUE THREAD

**Issue by robertofd1995** [robertofd1995/ShareMyTrip#7]
Una vez que el usuario ha seleccionado un viaje en el que está interesado (Caso de uso
“Consultar viajes”) podrá solicitar plaza en él. El viaje le aparecerá entonces en el listado de
viajes en los que ha tenido alguna implicación (como promotor, participante o interesado).
OPCIONAL C: El usuario podrá filtrar el listado anterior para localizar
rápidamente los viajes de su interés. (hasta 0,5 puntos).
OPCIONAL D: El usuario podrá seleccionar el tipo de ordenación para los viajes:
origen, destino, fecha, promotor, etc. (hasta 0,5 puntos).

Por cada viaje aparecerá una entrada en el listado que especificará: el viaje, la fecha y
el estado de su relación con el viaje (PROMOTOR, PENDIENTE, ADMITIDO,
SIN_PLAZA, EXCLUIDO).
El usuario podrá cancelar su solicitud de plaza en los viajes aún pendientes haya
sido confirmado o no.

**Comment by damianplz** [comment]
Mejorar lógica:
-Un usuario no puede solicitar plaza en sus viajes
-Un usuario no puede solicitar plaza en viajes pasados
-Un usuario no puede solicitar plaza en viajes sin plazas libres
